#!/usr/bin/env python3
"""Deterministic OKF `index.md` generator for a single folder.

Parses a folder's concept documents (their YAML frontmatter) and renders — or
idempotently updates — a consistent, OKF-conformant `index.md`. `index.md` is an
OKF reserved file: frontmatter-free, EXCEPT the bundle root (`docs/`), which
carries only `okf_version`. Re-running with no document changes produces
byte-identical output (no volatile timestamps), so it is safe in a pre-commit
hook or an audit `--check`.

Summary source per document, in priority order:
  1. the document's OKF `description` frontmatter field (preferred — reusable,
     OKF-native, single source of truth);
  2. a preserved manual cell from the existing index (only when the doc has no
     `description`);
  3. a `_TODO summarize_` placeholder — reported on stdout so the caller (the
     util-docs-index skill) can read the doc, write a concise `description:` into
     it, and re-run.

Usage:
  gen_index.py <folder> [--check] [--okf-version X]
    --check           report-only; exit 1 if the index would change (hooks/audit)
    --okf-version X    force bundle-root frontmatter `okf_version: "X"`

Exit codes: 0 ok / up-to-date · 1 (with --check) index would change · 2 usage/error.
Standard library only.
"""
import os
import re
import sys

RESERVED = {"index.md", "log.md", "README.md"}
# Transient / non-content directories never listed as subfolders.
SKIP_DIRS = {"__pycache__", ".venv", "node_modules", ".git", ".pytest_cache", "__marimo__"}
PLACEHOLDER = "_TODO summarize_"


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def parse_frontmatter(text):
    """Return the leading YAML frontmatter as a dict of scalar key -> value."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm = {}
    for line in text[3:end].splitlines():
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if len(val) >= 2 and val[0] in "\"'" and val[-1] == val[0]:
            val = val[1:-1]
        fm[key] = val
    return fm


def parse_existing(text):
    """From an existing index: (filename -> summary cell, okf_version or None)."""
    summaries = {}
    okf = parse_frontmatter(text).get("okf_version")
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        m = re.search(r"\]\(([^)]+)\)", cells[1])  # the [title](file.md) cell
        if not m:
            continue
        summaries[os.path.basename(m.group(1))] = cells[3]
    return summaries, okf


def esc(text):
    return text.replace("|", r"\|").replace("\n", " ").strip()


def build(folder, okf_force=None):
    idx_path = os.path.join(folder, "index.md")
    existing = read(idx_path)
    prev_sum, prev_okf = parse_existing(existing)

    is_root = os.path.basename(folder) == "docs"
    okf = okf_force or prev_okf or ("0.1" if is_root else None)

    docs = sorted(
        f for f in os.listdir(folder)
        if f.endswith(".md") and f not in RESERVED
        and os.path.isfile(os.path.join(folder, f))
    )
    subdirs = sorted(
        d for d in os.listdir(folder)
        if os.path.isdir(os.path.join(folder, d))
        and not d.startswith(".") and d not in SKIP_DIRS
    )

    rows, needs = [], []
    for fn in docs:
        fm = parse_frontmatter(read(os.path.join(folder, fn)))
        desc = fm.get("description", "").strip()
        prev = prev_sum.get(fn, "")
        if desc:
            summary = desc
        elif prev and PLACEHOLDER not in prev:
            summary = prev
        else:
            summary = PLACEHOLDER
            needs.append(fn)
        rows.append((
            esc(fm.get("type", "—")),
            esc(fm.get("title", fn)),
            fn,
            esc(fm.get("status", "—")),
            esc(summary),
        ))

    heading = "Documentation index" if is_root else f"{os.path.basename(folder)}/ — index"
    out = []
    if okf:
        out += ["---", f'okf_version: "{okf}"', "---", ""]
    out += [f"# {heading}", ""]
    out += ["<!-- OKF reserved index — generated by util-docs-index (scripts/gen_index.py). "
            "Frontmatter-free except the bundle-root okf_version. "
            "Summaries come from each doc's OKF `description`; regenerate after edits. -->", ""]
    out += ["| Type | Document | Status | Summary |", "|---|---|---|---|"]
    for typ, title, fn, status, summary in rows:
        out.append(f"| {typ} | [{title}]({fn}) | {status} | {summary} |")
    if subdirs:
        out += ["", "## Subfolders", ""]
        for d in subdirs:
            if os.path.isfile(os.path.join(folder, d, "index.md")):
                out.append(f"- [{d}/]({d}/index.md)")
            else:
                out.append(f"- {d}/ — _(no index yet)_")
    footer = f"> {len(rows)} document(s)"
    if subdirs:
        footer += f" · {len(subdirs)} subfolder(s)"
    out += ["", footer, ""]
    return idx_path, existing, "\n".join(out), needs


def main(argv):
    check = "--check" in argv
    argv = [a for a in argv if a != "--check"]
    okf_force = None
    if "--okf-version" in argv:
        i = argv.index("--okf-version")
        try:
            okf_force = argv[i + 1]
        except IndexError:
            sys.stderr.write("--okf-version needs a value\n")
            return 2
        del argv[i:i + 2]
    if not argv:
        sys.stderr.write("usage: gen_index.py <folder> [--check] [--okf-version X]\n")
        return 2
    folder = argv[0].rstrip("/")
    if not os.path.isdir(folder):
        sys.stderr.write(f"not a directory: {folder}\n")
        return 2

    idx_path, existing, content, needs = build(folder, okf_force)

    if check:
        if content != existing:
            sys.stderr.write(f"STALE INDEX: {idx_path} would change — run util-docs-index\n")
            return 1
        print(f"up to date: {idx_path}")
        return 0

    if content == existing:
        print(f"unchanged: {idx_path}")
    else:
        with open(idx_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {idx_path}")
    if needs:
        print("NEEDS SUMMARY (write a concise `description:` into each doc, then re-run):")
        for fn in needs:
            print(f"  - {fn}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
