#!/usr/bin/env python3
"""Deterministic OKF `log.md` generator for a single folder, derived from git.

`log.md` is an OKF v0.1 reserved file: a per-directory chronological change
history, for consumers that don't have the git repo (tarball/zip bundles). It is
rendered as a **materialized view of `git log`** for the folder's direct-child
documents — nothing is hand-appended, so it is deterministic (same committed
history -> byte-identical output; no volatile "now" timestamps).

OKF-prescribed format (SPEC.md): a flat list of date-grouped entries, newest
first; ISO 8601 `## YYYY-MM-DD` date headings; prose bullets; a leading bold
action word (`**Update**`/`**Creation**`/`**Deprecation**`) — here derived from
git's add/modify/delete status. `log.md` carries no frontmatter.

Model: **one bullet per commit** (as-is — the commit subject), listing the
subset of THIS folder's documents it touched as inline links. A commit that
spans several folders appears in each affected folder's log, scoped to its files.

Scope: **non-recursive** — the folder's direct-child `*.md` docs only (excludes
reserved `index.md`/`log.md`/`README.md`). Subtree history lives in each
subfolder's own `log.md`.

Usage:
  gen_log.py <folder> [--check] [--max N]
    --check     report-only; exit 1 if log.md would change (audit / drift)
    --max N     cap at the N most recent commits (default: all)

Exit: 0 ok / up-to-date · 1 (--check) would change · 2 usage/error / not a git repo.
Standard library only.
"""
import os
import subprocess
import sys

RESERVED = {"index.md", "log.md", "README.md"}
US, RS = "\x1f", "\x1e"  # field / record separators
LABEL = {"A": "Creation", "D": "Deprecation"}  # single-status commits; else Update


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def git(folder, *args):
    try:
        out = subprocess.run(
            ["git", "-C", folder, *args],
            capture_output=True, text=True, check=True,
        )
        return True, out.stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False, ""


def label_for(statuses):
    kinds = {s[0] for s in statuses}
    if kinds == {"A"}:
        return "Creation"
    if kinds == {"D"}:
        return "Deprecation"
    return "Update"


def build(folder, max_n=None):
    idx_path = os.path.join(folder, "log.md")
    docs = sorted(
        f for f in os.listdir(folder)
        if f.endswith(".md") and f not in RESERVED
        and os.path.isfile(os.path.join(folder, f))
    )
    known = set(docs)
    title = ["# Directory Update Log", "",
             "<!-- OKF reserved log — generated by util-docs-log from git history "
             "(scripts/gen_log.py). Non-recursive: this folder's direct docs only. -->", ""]

    if not docs:
        return idx_path, read(idx_path), "\n".join(title + ["> no documents", ""]), None

    ok, _ = git(folder, "rev-parse", "--is-inside-work-tree")
    if not ok:
        return idx_path, read(idx_path), None, "not a git repository"

    fmt = f"{RS}%h{US}%ad{US}%s"
    args = ["log", "--no-merges", "--date=short", f"--pretty=format:{fmt}", "--name-status"]
    if max_n:
        args += ["-n", str(max_n)]
    args += ["--", *docs]
    ok, raw = git(folder, *args)
    if not ok:
        return idx_path, read(idx_path), None, "git log failed"

    commits = []  # (date, hash, subject, [files], label)
    for rec in raw.split(RS):
        rec = rec.strip("\n")
        if not rec:
            continue
        lines = rec.split("\n")
        parts = lines[0].split(US)
        if len(parts) != 3:
            continue
        h, date, subject = parts
        files, statuses = [], []
        for ln in lines[1:]:
            if not ln.strip():
                continue
            cols = ln.split("\t")
            status, path = cols[0], cols[-1]  # cols[-1] handles rename "R old new"
            base = os.path.basename(path)
            if base in known and base not in files:
                files.append(base)
                statuses.append(status)
        if not files:
            continue
        commits.append((date, h, subject.replace("\n", " ").strip(),
                        sorted(files), label_for(statuses)))

    out = list(title)
    if not commits:
        out += ["> no history yet", ""]
        return idx_path, read(idx_path), "\n".join(out), None

    last_date = None
    for date, h, subject, files, label in commits:
        if date != last_date:
            out += ["", f"## {date}", ""]
            last_date = date
        links = ", ".join(f"[{f}]({f})" for f in files)
        out.append(f"* **{label}**: {subject} ({links}) — `{h}`")
    out += [""]
    return idx_path, read(idx_path), "\n".join(out), None


def main(argv):
    check = "--check" in argv
    argv = [a for a in argv if a != "--check"]
    max_n = None
    if "--max" in argv:
        i = argv.index("--max")
        try:
            max_n = int(argv[i + 1])
        except (IndexError, ValueError):
            sys.stderr.write("--max needs an integer\n")
            return 2
        del argv[i:i + 2]
    if not argv:
        sys.stderr.write("usage: gen_log.py <folder> [--check] [--max N]\n")
        return 2
    folder = argv[0].rstrip("/")
    if not os.path.isdir(folder):
        sys.stderr.write(f"not a directory: {folder}\n")
        return 2

    idx_path, existing, content, err = build(folder, max_n)
    if err or content is None:
        sys.stderr.write(f"skip {idx_path}: {err or 'no content'}\n")
        return 2

    if check:
        if content != existing:
            sys.stderr.write(f"STALE LOG: {idx_path} would change — run util-docs-log\n")
            return 1
        print(f"up to date: {idx_path}")
        return 0

    if content == existing:
        print(f"unchanged: {idx_path}")
    else:
        with open(idx_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {idx_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
