#!/usr/bin/env python3
"""Render the kit's AGENTS.md adapter block into harness instruction files.

Writes a marker-delimited block (template + concatenated behavioural rules) into each
target file, creating the file if absent and replacing only the marked block otherwise.
User content outside the markers is never touched. Idempotent.

Usage: gen-agents-md.py <kit_dir> <target_file> [<target_file> ...]
"""
import re
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN homemade-claude-kit adapter (generated by install.sh — do not edit inside markers) -->"
END = "<!-- END homemade-claude-kit adapter -->"

# Harness-agnostic behavioural rules, concatenated in this order. Metamodel rules are
# excluded on purpose: they are Claude pointer stubs; the routing paragraph in the
# template covers other harnesses (kit ADR-0006 §4, ADR-0007 §6).
BEHAVIOURAL_RULES = [
    "working-style.md",
    "git-and-tools.md",
    "writing-citations.md",
    "diagramming-mermaid.md",
    "frontend-nuxt.md",
]


def strip_frontmatter(text: str) -> str:
    return re.sub(r"\A---\n.*?\n---\n+", "", text, flags=re.S)


def build_block(kit: Path) -> str:
    parts = [(kit / "templates" / "agents-adapter.md").read_text().rstrip()]
    for name in BEHAVIOURAL_RULES:
        p = kit / "rules" / name
        if p.is_file():
            parts.append("\n---\n\n" + strip_frontmatter(p.read_text()).rstrip())
    return BEGIN + "\n\n" + "\n".join(parts) + "\n\n" + END


def install(target: Path, block: str) -> str:
    if target.is_file():
        text = target.read_text()
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if pattern.search(text):
            new = pattern.sub(lambda _: block, text)
            action = "updated"
        else:
            sep = "\n\n" if text and not text.endswith("\n\n") else ""
            new = text + sep + block + "\n"
            action = "appended"
        if new == text:
            return "unchanged"
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        new = block + "\n"
        action = "created"
    target.write_text(new)
    return action


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 1
    kit = Path(sys.argv[1])
    block = build_block(kit)
    for raw in sys.argv[2:]:
        target = Path(raw).expanduser()
        print(f"  adapter {install(target, block)}: {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
