#!/usr/bin/env python3
"""Project mcp/registry.json into the three harness declaration formats (kit ADR-0006 §4).

Subcommands:
  plugins  <kit_dir>          Write per-plugin .mcp.json files (committed; consumed by the
                              Claude marketplace so a plugin toggle carries its MCP servers).
  harness  <kit_dir> <home>   Write the Codex config.toml marker block and merge the
                              OpenCode opencode.json `mcp` key. Only enabled servers are
                              emitted; registry-known names are removed when disabled.

Idempotent; user content outside the managed surfaces is never touched.
"""
import json
import re
import sys
from pathlib import Path

TOML_BEGIN = "# BEGIN homemade-claude-kit mcp (generated by install.sh — do not edit inside markers)"
TOML_END = "# END homemade-claude-kit mcp"


def load(kit: Path):
    return json.loads((kit / "mcp" / "registry.json").read_text())


def gen_plugins(kit: Path) -> None:
    reg = load(kit)
    by_set: dict[str, dict] = {}
    for s in reg["servers"]:
        if not s["enabled"]:
            continue
        t = s["transport"]
        entry = {"command": t["command"], "args": t["args"]} if t["type"] == "stdio" else {"type": "http", "url": t["url"]}
        if "env" in t:
            entry["env"] = t["env"]
        by_set.setdefault(s["owning_set"], {})[s["name"]] = entry
    for plugin_dir in sorted((kit / "plugins").iterdir()):
        target = plugin_dir / ".mcp.json"
        servers = by_set.get(plugin_dir.name)
        if servers:
            target.write_text(json.dumps({"mcpServers": servers}, indent=2) + "\n")
            print(f"  mcp written: {target}")
        elif target.exists():
            target.unlink()
            print(f"  mcp removed: {target}")


def toml_block(reg) -> str:
    lines = [TOML_BEGIN]
    for s in reg["servers"]:
        if not s["enabled"]:
            continue
        t = s["transport"]
        if t["type"] != "stdio":
            lines.append(f"# {s['name']}: http transport not declared for Codex — enable manually if supported")
            continue
        lines.append(f"[mcp_servers.{s['name']}]")
        lines.append(f'command = "{t["command"]}"')
        lines.append("args = [" + ", ".join(f'"{a}"' for a in t["args"]) + "]")
        env = t.get("env", {})
        if env:
            entries = ", ".join(f'"{k}" = "{v}"' for k, v in env.items())
            lines.append(f"env = {{ {entries} }}")
    lines.append(TOML_END)
    return "\n".join(lines)


def write_codex(reg, home: Path) -> None:
    target = home / ".codex" / "config.toml"
    block = toml_block(reg)
    if target.is_file():
        text = target.read_text()
        pattern = re.compile(re.escape(TOML_BEGIN) + r".*?" + re.escape(TOML_END), re.S)
        new = pattern.sub(lambda _: block, text) if pattern.search(text) else text.rstrip() + "\n\n" + block + "\n"
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        new = block + "\n"
    if not target.is_file() or new != target.read_text():
        target.write_text(new)
    print(f"  codex mcp block: {target}")


def write_opencode(reg, home: Path) -> None:
    target = home / ".config" / "opencode" / "opencode.json"
    config = json.loads(target.read_text()) if target.is_file() else {"$schema": "https://opencode.ai/config.json"}
    mcp = config.get("mcp", {})
    for s in reg["servers"]:
        if s["enabled"]:
            t = s["transport"]
            if t["type"] == "stdio":
                entry = {"type": "local", "command": [t["command"], *t["args"]], "enabled": True}
                if "env" in t:
                    entry["environment"] = t["env"]
            else:
                entry = {"type": "remote", "url": t["url"], "enabled": True}
            mcp[s["name"]] = entry
        else:
            mcp.pop(s["name"], None)   # registry-known but disabled -> managed removal
    if mcp:
        config["mcp"] = mcp
    else:
        config.pop("mcp", None)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(config, indent=2) + "\n")
    print(f"  opencode mcp key: {target}")


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 1
    cmd, kit = sys.argv[1], Path(sys.argv[2])
    reg = load(kit)
    if cmd == "plugins":
        gen_plugins(kit)
    elif cmd == "harness":
        home = Path(sys.argv[3]).expanduser() if len(sys.argv) > 3 else Path.home()
        write_codex(reg, home)
        write_opencode(reg, home)
    else:
        print(f"unknown subcommand: {cmd}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
